# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyIVxxQdvNOZMhfWQOJ6kp23-3-EgNXK
"""

import tensorflow as tf
import numpy as np

# Create a random 4x4 matrix with integers (e.g., between 0 and 9)
input_matrix = np.random.randint(0, 10, size=(4, 4)).astype(np.float32)
print("Original Matrix:\n", input_matrix)

# Reshape the input matrix to match TensorFlow's expected format
# TensorFlow expects (batch_size, height, width, channels)
input_matrix = input_matrix.reshape(1, 4, 4, 1)  # Batch size = 1, Channels = 1

# Define a Max Pooling layer with a 2x2 pool size
max_pool = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid')

# Apply Max Pooling
max_pooled_matrix = max_pool(input_matrix).numpy().squeeze()
print("\nMax-Pooled Matrix:\n", max_pooled_matrix)

# Define an Average Pooling layer with a 2x2 pool size
avg_pool = tf.keras.layers.AveragePooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid')

# Apply Average Pooling
avg_pooled_matrix = avg_pool(input_matrix).numpy().squeeze()
print("\nAverage-Pooled Matrix:\n", avg_pooled_matrix)