# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import spacy

def perform_ner(sentence):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(sentence)

    for ent in doc.ents:
        print(f"Entity: {ent.text}, Label: {ent.label_}, Start: {ent.start_char}, End: {ent.end_char}")

# Test the function
sentence = "Barack Obama served as the 44th President of the United States and won the Nobel Peace Prize in 2009."
perform_ner(sentence)